resetDelay: 5 # This is the reset delay in minutes.
structureFile: "structure" # This is the structure file name without the .dat on the end!
autoResets: true # Should the plugin auto-reset the mines?
teleportToMineFromVoid: true # Should players be teleported to their mines if they fall in the void?
floorOffset: 1

# Options
# - BUKKIT
# - NMS_SAFE
# - NMS_FAST
# - NMS_UNSAFE

mineFillSpeed: BUKKIT

materials:
  COBBLESTONE: 1
  STONE: 5

# Put the mine types in the order you want them to rank up in :)

mineTypes:
  Type1:
    file: structure.dat
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
  Type2:
    file: structure2.dat
    materials:
      STONE: 1.0
      COBBLESTONE: 2.0
      EMERALD_BLOCK: 0.3