resetDelay: 5 # This is the reset delay in minutes.
structureFile: "structure" # This is the structure file name without the .dat on the end!
autoResets: true # Should the plugin auto-reset the mines?
teleportToMineFromVoid: true # Should players be teleported to their mines if they fall in the void?
floorOffset: 1

# Options
# - BUKKIT
# - NMS_SAFE
# - NMS_FAST
# - NMS_UNSAFE

mineFillSpeed: BUKKIT

materials:
  COBBLESTONE: 1
  STONE: 5

# This is the list of all the mine types you want to have in your private mine
#
#
# An example of how to set up a mine type
#
#  Type1:                    - The top will be what it's called.
#    file: structure.dat     - This is the file of which the mine type will use
#    priority: 1             - This is the priority of the mine type (where it goes in the upgrade oder)
#    materials:              - The list of Materials, follow the order posted here
#      STONE: 0.9            - MATERIAL: (0.1 -> 1.0) - Value after the Material is the percent
#      COBBLESTONE: 0.1      - Example of a percent is 3.14159265359

mineTypes:
  Type1:
    file: structure.dat
    priority: 1
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
  Type2:
    file: structure2.dat
    priority: 2
    materials:
      STONE: 1.0
      COBBLESTONE: 2.0
      EMERALD_BLOCK: 0.3