name: PrivateMinesRewrite
version: 2.2.1-dev # Change this to update version
main: me.untouchedodin0.privatemines.PrivateMines
author: UntouchedOdin0
api-version: 1.13

depend:
  - RedLib
softdepend:
  - PlaceholderAPI